### PR TITLE
clarify usage

### PR DESCRIPTION
**Pull request by skywinder**
to avoid this
https://addons.mozilla.org/en-GB/firefox/addon/window-merger/reviews/1602333/

### CODE REVIEW

**Comment by Zegnat** [comment]
I am wondering if this should go higher up in the file 🤔 Do people read my long rambling intro all the way first?

**Comment by skywinder** [comment]
1) it's better than nothing.
2) for me it's clear enoght. first that i do - i'm looking "Usage" section.
3) feel free to update 👍

**Comment by skywinder** [comment]
but I agree. Alternatives could be placed lower. it's no so important.

**Comment by skywinder** [comment]
Don't forget to update Firefox page to 👍

**Comment by Zegnat** [comment]
Sorry to have left this hanging. This whole thing got me thinking about a bunch of different aspects of making the extension more easily discovered (e.g. putting it in the Tools menu, #11.)

During the last week I have been dipping into it and chipping away at this little by little. Could you have a look at my current README and tell me what you think?

* The start of the README has been updated to more explicitly mention how the extension is likely to be used (right-clicking). I think I prefer this over having a separate section elsewhere and will hopefully flow better on the AMO page too.
* The extension will also add itself to Tools, and a screenshot of this has been added to the README.
* By default, right-clicking within the tab bar will now also trigger the extension's context menu. Previously this had to be configured through the extension preferences.

**Comment by Zegnat** [comment]
My changes have gone live both here in GitHub but also on the AMO page, with new text and new screenshots, as per [v0.6.0](https://github.com/Zegnat/browserext-window-merger/releases/tag/v0.6.0). Going to close this PR for now.

**Pull request closed without merging**
